name = "finance-telegram-mini-app"
main = "src/worker.ts"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-12"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "finance-db"
database_id = "034ed859-d408-41bc-958b-d5bf37a4ace2"
migrations_dir = "migrations"

[vars]
APP_ORIGIN = "https://planfinance.pages.dev"
TELEGRAM_AUTH_MAX_AGE_SECONDS = "86400"

[triggers]
crons = ["0 * * * *", "5 0 * * *"]
