CREATE TABLE assets (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, symbol TEXT NOT NULL, name TEXT NOT NULL, asset_class TEXT NOT NULL CHECK(asset_class IN ('stock','etf','gold','crypto','other')), unit TEXT NOT NULL DEFAULT 'unit', manual_price_satang INTEGER, price_updated_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, symbol));
CREATE INDEX assets_user_idx ON assets(user_id);
CREATE TABLE investment_transactions (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, asset_id TEXT NOT NULL REFERENCES assets(id), account_id TEXT NOT NULL REFERENCES accounts(id), type TEXT NOT NULL CHECK(type IN ('buy','sell','deposit','withdraw','dividend','fee')), quantity_micros INTEGER NOT NULL, price_satang INTEGER NOT NULL DEFAULT 0, total_satang INTEGER NOT NULL, fee_satang INTEGER NOT NULL DEFAULT 0, transaction_date TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX investment_user_asset_idx ON investment_transactions(user_id, asset_id, transaction_date);
CREATE TABLE portfolio_targets (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, asset_class TEXT NOT NULL, target_percent_basis_points INTEGER NOT NULL CHECK(target_percent_basis_points BETWEEN 0 AND 10000), max_percent_basis_points INTEGER, PRIMARY KEY(user_id, asset_class));
CREATE TABLE vehicles (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, current_value_satang INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE fuel_logs (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, vehicle_id TEXT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE, log_date TEXT NOT NULL, odometer_km INTEGER NOT NULL, liters_micros INTEGER NOT NULL, price_per_liter_satang INTEGER NOT NULL, total_satang INTEGER NOT NULL, station TEXT, note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX fuel_vehicle_date_idx ON fuel_logs(vehicle_id, log_date DESC);
CREATE TABLE net_worth_snapshots (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, snapshot_month TEXT NOT NULL, total_assets_satang INTEGER NOT NULL, total_liabilities_satang INTEGER NOT NULL, net_worth_satang INTEGER NOT NULL, liquid_assets_satang INTEGER NOT NULL, investments_satang INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, snapshot_month));
